export enum Colors {
  RED = "red",
  ORANGE = "orange",
  AMBER = "amber",
  YELLOW = "yellow",
  LIME = "lime",
  GREEN = "green",
  EMERALD = "emerald",
  TEAL = "teal",
  CYAN = "cyan",
  LIGHT_BLUE = "light-blue",
  BLUE = "blue",
  INDIGO = "indigo",
  VIOLET = "violet",
  PURPLE = "purple",
  FUCHSIA = "fuchsia",
  ROSE = "rose",
  WARM_GRAY = "warm-gray",
  TRUE_GRAY = "true-gray",
  GRAY = "gray",
  COOL_GRAY = "cool-gray",
  BLUE_GRAY = "blue-gray",
}
